go:
	xsltproc elementlist.xsl /TEI/Sourceforge/P5/Source-driver.xml > elements.xml
	xsltproc classlist.xsl /TEI/Sourceforge/P5/Source-driver.xml > classes.xml
	xsltproc macrolist.xsl /TEI/Sourceforge/P5/Source-driver.xml > macros.xml
	xsltproc modulelist.xsl /TEI/Sourceforge/P5/Source-driver.xml > modules.xml
